name: CD
on:
    push:
        branches:
            - main
jobs:
    Build:
        runs-on: ubuntu-latest
        name: Build Vue
        steps:
            - uses: actions/checkout@v2
            - id: Build-Vue
              uses: xRealNeon/VuePagesAction@1.0.1
              with:
                  username: 'khateeboveskey'
                  reponame: 'mersal-crms'
                  token: ${{ secrets.GITHUB_TOKEN }}
                  gitemail: 'khateeboveskey@gmail.com'
                  gitname: 'khateeboveskey'
